### ISSUE TITLE
UniqueColorGenerator bug

### ISSUE THREAD

**Issue by BastardFat** [EynsherKiel/Twill#3]
Hello. I found a small bug in your code. In **`GetUniqueBrush`** you check if **`List<Brush>`** contains some new **`Brush`**:
![image](https://cloud.githubusercontent.com/assets/23219786/21976538/66c7d4e6-dbe3-11e6-90e1-fa74f9ff7a4d.png)
But **`SolidColorBrush`** is class:
![image](https://cloud.githubusercontent.com/assets/23219786/21976562/85b325cc-dbe3-11e6-8b1f-c2d334484a85.png)
Therefore **`Contains`** will check the equality of object references, that are always different.

I suggest replacing this code:
**`while (Brushes.Contains(resultBrush));`**
with this code:
**`while (Brushes.Any(brush => (Math.Abs(resultBrush.Color.R - brush.Color.R) + Math.Abs(resultBrush.Color.G - brush.Color.G) + Math.Abs(resultBrush.Color.B - brush.Color.B)) < 60));`**

In addition, it checks not only the equality, but the similarity

**Comment by EynsherKiel** [comment]
Thank.
